### ISSUE TITLE
erro r# E (1685) i2c: i2c_set_pin(827): scl and sda gpio numbers are the same

### ISSUE THREAD

**Issue by leonvita91** [epvuc/esp-fume-detector#1]
hello,
may you help please because i cant understand how this code works,it should showing the temp on the monitor but on the monitor gave me only this error . 

I (0) cpu_start: App cpu up.
I (486) cpu_start: Pro cpu start user code
I (486) cpu_start: cpu freq: 160000000
I (486) cpu_start: Application information:
I (491) cpu_start: Project name:     wifi_manager
I (496) cpu_start: App version:      2f6a447-dirty
I (502) cpu_start: Compile time:     May  3 2021 13:41:32
I (508) cpu_start: ELF file SHA256:  d249ae81352c93d0...
I (514) cpu_start: ESP-IDF:          v4.4-dev-1183-g9d34a1cd4
I (520) heap_init: Initializing. RAM available for dynamic allocation:
I (527) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (533) heap_init: At 3FFB76D8 len 00028928 (162 KiB): DRAM
I (540) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (546) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (552) heap_init: At 40095D48 len 0000A2B8 (40 KiB): IRAM
I (560) spi_flash: detected chip: generic
I (563) spi_flash: flash io: dio
I (568) sleep: Configure to isolate all GPIO pins in sleep state
I (574) sleep: Enable automatic switching of GPIO sleep configuration
I (582) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
http_server: waiting for start bit
E (685) i2c: i2c_param_config(646): i2c clock choice is invalid, please check flag and frequency
calling bme280_init
I (695) wifi:wifi driver task: 3ffc35f0, prio:23, stack:6656, core=0
I (695) system_api: Base MAC address is not set
I (695) system_api: read default base MAC address from EFUSE
I (725) wifi:wifi firmware version: 0aebefd
I (725) wifi:wifi certification version: v7.0
I (725) wifi:config NVS flash: enabled
I (725) wifi:config nano formating: disabled
I (725) wifi:Init data frame dynamic rx buffer num: 32
I (735) wifi:Init management frame dynamic rx buffer num: 32
I (735) wifi:Init management short buffer num: 32
I (745) wifi:Init dynamic tx buffer num: 32
I (745) wifi:Init static rx buffer size: 1600
I (755) wifi:Init static rx buffer num: 10
I (755) wifi:Init dynamic rx buffer num: 32
I (755) wifi_init: rx ba win: 6
I (765) wifi_init: tcpip mbox: 32
I (765) wifi_init: udp mbox: 6
I (765) wifi_init: tcp mbox: 6
I (775) wifi_init: tcp tx win: 5744
I (775) wifi_init: tcp rx win: 5744
I (785) wifi_init: tcp mss: 1440
I (785) wifi_init: WiFi IRAM OP enabled
I (795) wifi_init: WiFi RX IRAM OP enabled
I (1525) phy_init: phy_version 4670,719f9f6,Feb 18 2021,17:07:07
I (1625) wifi:mode : sta (ac:67:b2:2b:fb:14) + softAP (ac:67:b2:2b:fb:15)
I (1635) wifi:enable tsf
I (1635) wifi:Total power save buffer number: 16
I (1635) wifi:Init max length of beacon: 752/752
I (1635) wifi:Init max length of beacon: 752/752
wifi_mamager: starting softAP with ssid MEWO
wifi_mamager: softAP started, starting http_server
http_server: received start bit, starting server
HTTP Server listening...
E (1685) i2c: i2c_set_pin(827): scl and sda gpio numbers are the same
E (2685) i2c: i2c_set_pin(827): scl and sda gpio numbers are the same
E (3685) i2c: i2c_set_pin(827): scl and sda gpio numbers are the same
E (4685) i2c: i2c_set_pin(827): scl and sda gpio numbers are the same
E (5685) i2c: i2c_set_pin(827): scl and sda gpio numbers are the same
bme280 init result -2
E (6685) i2c: i2c_set_pin(827): scl and sda gpio numbers are the same
bme280 settings config result -4
E (7685) i2c: i2c_set_pin(827): scl and sda gpio numbers are the same
E (8725) i2c: i2c_set_pin(827): scl and sda gpio numbers are the same
I (8725) BME280: bme280_get_sensor_data() returned -4
E (9725) i2c: i2c_set_pin(827): scl and sda gpio numbers are the same
E (10725) i2c: i2c_set_pin(827): scl and sda gpio numbers are the same
E (11725) i2c: i2c_set_pin(827): scl and sda gpio numbers are the same
I (11725) FUME: Fumes: f:17603 t:32.00 p:0.0000 h:0.0 #0

**Comment by epvuc** [comment]
It appears that i2c_setup thinks the pin setup for SCL and SDA lines aren't correct. They should be set as SCL_PIN and SDA_PIN in bme280_supp.c (and the same in ads1110.c)

Also consider looking at https://github.com/epvuc/fumething-new which is updated for more recent esp-idf versions.

**Comment by leonvita91** [comment]
thank you i had already fix all the code error and make the right pins i really appreciate your answer  :+1:
